name: Kick VOD Downloader

on:
workflow_dispatch:
inputs:
vod_url:
description: 'Kick VOD link'
required: true
default: 'https://kick.com/video/example'

jobs:
download:
runs-on: ubuntu-latest
steps:
- name: Set up environment
run: sudo apt-get update && sudo apt-get install -y ffmpeg python3 python3-pip

- name: Install yt-dlp
run: pip3 install yt-dlp

- name: Download VOD
run: yt-dlp "${{ github.event.inputs.vod_url }}" -o "kick_vod.mp4"

- name: Upload as artifact
uses: actions/upload-artifact@v3
with:
name: kick_vod
path: kick_vod.mp4
