name: Kick VOD Downloader

on:
workflow_dispatch:
inputs:
vod_url:
description: "Paste the full Kick VOD link"
required: true
default: ""

jobs:
download:
runs-on: ubuntu-latest

steps:
- name: Checkout repo
uses: actions/checkout@v3

- name: Install yt-dlp
run: |
sudo apt update
sudo apt install -y python3-pip
pip install yt-dlp

- name: Download Kick VOD
run: |
yt-dlp "${{ github.event.inputs.vod_url }}" -o "kick_vod.mp4"

- name: Upload as Artifact
uses: actions/upload-artifact@v3
with:
name: kick_vod
path: kick_vod.mp4
