name: Download Kick VOD

on:
workflow_dispatch:
inputs:
vod_url:
description: 'Kick VOD URL'
required: true

jobs:
download:
runs-on: ubuntu-latest
steps:
- name: Install yt-dlp
run: |
sudo apt update
sudo apt install -y python3-pip
pip3 install yt-dlp

- name: Download Kick VOD
run: yt-dlp -f best "${{ github.event.inputs.vod_url }}" -o "kickvod.mp4"

- name: Upload MP4
uses: actions/upload-artifact@v3
with:
name: kickvod
path: kickvod.mp4
