name: Kick VOD Downloader

on:
workflow_dispatch:
inputs:
vod_link:
description: "Paste the Kick VOD link here"
required: true
type: string

jobs:
download:
runs-on: ubuntu-latest
steps:
- name: Checkout repo
uses: actions/checkout@v3

- name: Install yt-dlp
run: |
python3 -m pip install --upgrade pip
pip install yt-dlp

- name: Download VOD
run: |
yt-dlp "${{ github.event.inputs.vod_link }}" -o "vod.mp4"

- name: Upload VOD as Artifact
uses: actions/upload-artifact@v3
with:
name: kick-vod
path: vod.mp4
